db.jugadores.insertMany([

   {
       Jugador:"Kylian Mbappe",
       Nacionalidad:"Francia",
       Liga:"Liga Francesa",
       Equipo: "Paris Saint Germain",
       Edad: 21,
       PosicionPrincipal:"Extremo Izquierdo",
       PosicionesSecundarias:["Delantero Centro","Extremo Derecho"],
       PieHabil:"Derecho",
       Valor: 180000000, 
       Estadisticas:{Partidos: 37,Goles: 30,Asistencias: 19 },
       Altura: 1.78,

     } ,

     {
        Jugador:"Neymar Jr",
        Nacionalidad:"Brasil",
        Liga:"Liga Francesa",
        Equipo: "Paris Saint Germain",
        Edad: 28,
        PosicionPrincipal:"Extremo Izquierdo",
        PosicionesSecundarias:["Mediapunta","Delantero Centro"],
        PieHabil:"Derecho",
        Valor: 128000000, 
        Estadisticas:{Partidos: 27,Goles: 19,Asistencias: 12 },
        Altura: 1.75,
      } ,

      {
        Jugador:"Lionel Messi",
        Nacionalidad:"Argentina",
        Liga:"Liga Española",
        Equipo: "FC Barcelona",
        Edad: 33,
        PosicionPrincipal:"Extremo Derecho",
        PosicionesSecundarias:["Delantero Centro","Mediapunta"],
        PieHabil:"Izquierdo",
        Valor: 100000000, 
        Estadisticas:{Partidos: 44,Goles: 31,Asistencias: 27 },
        Altura: 1.70,
      } ,

      {
        Jugador:"Raheem Sterling",
        Nacionalidad:"Inglaterra",
        Liga:"Liga Inglesa",
        Equipo: "Manchester City",
        Edad: 25,
        PosicionPrincipal:"Extremo Izquierdo",
        PosicionesSecundarias:["Mediapunta","Extremo Derecho"],
        PieHabil:"Derecho",
        Valor: 128000000, 
        Estadisticas:{Partidos: 52,Goles: 31,Asistencias: 10 },
        Altura: 1.70,
      } ,

      {
        Jugador:"Sadio Mane",
        Nacionalidad:"Senegal",
        Liga:"Liga Inglesa",
        Equipo: "Liverpool FC",
        Edad: 28,
        PosicionPrincipal:"Extremo Izquierdo",
        PosicionesSecundarias:["Delantero Centro","Extremo Derecho"],
        PieHabil:"Derecho",
        Valor: 120000000, 
        Estadisticas:{Partidos: 47,Goles: 22,Asistencias: 12 },
        Altura: 1.74,
      } ,

      {
        Jugador:"Mohamed Salah",
        Nacionalidad:"Egipto",
        Liga:"Liga Inglesa",
        Equipo: "Liverpool FC",
        Edad: 28,
        PosicionPrincipal:"Extremo Derecho",
        PosicionesSecundarias:["Mediapunta","Extremo Izquierdo"],
        PieHabil:"Izquierdo",
        Valor: 120000000, 
        Estadisticas:{Partidos: 48,Goles: 23,Asistencias: 13 },
        Altura: 1.75,
      } ,

      {
        Jugador:"Erling Haaland",
        Nacionalidad:"Noruega",
        Liga:"Liga Alemana",
        Equipo: "Borussia Dortmund",
        Edad: 20,
        PosicionPrincipal:"Delantero Centro",
        PosicionesSecundarias:["Mediapunta"],
        PieHabil:"Izquierdo",
        Valor: 80000000, 
        Estadisticas:{Partidos: 40,Goles: 44,Asistencias: 10 },
        Altura: 1.94,
      } ,

      {
        Jugador:"Lucas Ocampos",
        Nacionalidad:"Argentina",
        Liga:"Liga Española",
        Equipo: "Sevilla FC",
        Edad: 26,
        PosicionPrincipal:"Extremo Derecho",
        PosicionesSecundarias:["Extremo Izquierdo"],
        PieHabil:"Derecho",
        Valor: 50000000, 
        Estadisticas:{Partidos:44,Goles: 17,Asistencias: 5 },
        Altura: 1.87,
      } ,

      {
        Jugador:"Ousmane Dembele",
        Nacionalidad:"Francia",
        Liga:"Liga Española",
        Equipo: "FC Barcelona",
        Edad: 23,
        PosicionPrincipal:"Extremo Derecho",
        PosicionesSecundarias:["Extremo Izquierdo"],
        PieHabil:"Izquierdo",
        Valor: 50000000, 
        Estadisticas:{Partidos: 9,Goles: 1,Asistencias: 0 },
        Altura: 1.78,
      } ,

      {
        Jugador:"Sergio Ramos",
        Nacionalidad:"España",
        Liga:"Liga Española",
        Equipo: "Real Madrid CF",
        Edad: 34,
        PosicionPrincipal:"Defensa Central",
        PosicionesSecundarias:["Lateral Derecho"],
        PieHabil:"Derecho",
        Valor: 14000000, 
        Estadisticas:{Partidos: 44,Goles: 13,Asistencias: 1 },
        Altura: 1.84,
      } ,

      {
        Jugador:"Marcelo",
        Nacionalidad:"Brasil",
        Liga:"Liga Española",
        Equipo: "Real Madrid CF",
        Edad: 32,
        PosicionPrincipal:"Lateral Izquierdo",
        PosicionesSecundarias:["Interior Izquierdo"],
        PieHabil:"Izquierdo",
        Valor: 12000000, 
        Estadisticas:{Partidos: 23,Goles: 2,Asistencias: 7 },
        Altura: 1.74,
      } ,

      {
        Jugador:"Gareth Bale",
        Nacionalidad:"Gales",
        Liga:"Liga Inglesa",
        Equipo: "Tottenham",
        Edad: 31,
        PosicionPrincipal:"Extremo Derecho",
        PosicionesSecundarias:["Delantero Centro","Extremo Izquierdo"],
        PieHabil:"Izquierdo",
        Valor: 25000000, 
        Estadisticas:{Partidos: 20,Goles: 3,Asistencias: 2 },
        Altura: 1.85,
      } ,

      {
        Jugador:"Cristiano Ronaldo",
        Nacionalidad:"Portugal",
        Liga:"Liga Italiana",
        Equipo: "Juventus",
        Edad: 35,
        PosicionPrincipal:"Extremo Izquierdo",
        PosicionesSecundarias:["Delantero Centro","Extremo Derecho"],
        PieHabil:"Derecho",
        Valor: 60000000, 
        Estadisticas:{Partidos: 46,Goles: 37,Asistencias: 7 },
        Altura: 1.87,
      } ,
      {
        Jugador:"Jesus Navas",
        Nacionalidad:"España",
        Liga:"Liga Española",
        Equipo: "Sevilla FC",
        Edad: 34,
        PosicionPrincipal:"Lateral Derecho",
        PosicionesSecundarias:["Extremo Derecho","Interior Derecho"],
        PieHabil:"Derecho",
        Valor: 3000000, 
        Estadisticas:{Partidos: 47,Goles: 0,Asistencias: 10 },
        Altura: 1.72,
      } ,
     
      {
        Jugador:"Joaquin Sanchez",
        Nacionalidad:"España",
        Liga:"Liga Española",
        Equipo: "Real Betis",
        Edad: 39,
        PosicionPrincipal:"Extremo Derecho",
        PosicionesSecundarias:["Extremo Izquierdo"],
        PieHabil:"Derecho",
        Valor: 1500000, 
        Estadisticas:{Partidos: 36,Goles: 10,Asistencias: 3 },
        Altura: 1.81,
      } ,

      {
        Jugador:"Zlatan Ibrahimovic",
        Nacionalidad:"Suecia",
        Liga:"Liga Italiana",
        Equipo: "AC Milan",
        Edad: 39,
        PosicionPrincipal:"Delantero Centro",
        PosicionesSecundarias:[],
        PieHabil:"Derecho",
        Valor: 3500000, 
        Estadisticas:{Partidos: 20,Goles: 11,Asistencias: 5 },
        Altura: 1.95,
      } ,

      {
        Jugador:"Virgil Van Dijk",
        Nacionalidad:"Holanda",
        Liga:"Liga Inglesa",
        Equipo: "Liverpool FC",
        Edad: 29,
        PosicionPrincipal:"Defensa Central",
        PosicionesSecundarias:[],
        PieHabil:"Derecho",
        Valor: 80000000, 
        Estadisticas:{Partidos: 50,Goles: 5,Asistencias: 2 },
        Altura: 1.93,
      } ,

      {
        Jugador:"Daniel Carvajal",
        Nacionalidad:"España",
        Liga:"Liga Española",
        Equipo: "Real Madrid CF",
        Edad: 28,
        PosicionPrincipal:"Lateral Derecho",
        PosicionesSecundarias:[],
        PieHabil:"Derecho",
        Valor: 40000000, 
        Estadisticas:{Partidos: 42,Goles: 1,Asistencias: 8 },
        Altura: 1.73,
      } ,

      {
        Jugador:"Joao Felix",
        Nacionalidad:"Portugal",
        Liga:"Liga Española",
        Equipo: "Atletico De Madrid",
        Edad: 21,
        PosicionPrincipal:"Mediapunta",
        PosicionesSecundarias:["Delantero Centro","Extremo Izquierdo"],
        PieHabil:"Derecho",
        Valor: 80000000, 
        Estadisticas:{Partidos: 36,Goles: 9,Asistencias: 3 },
        Altura: 1.80,
      } ,

      {
        Jugador:"Ansu Fati",
        Nacionalidad:"España",
        Liga:"Liga Española",
        Equipo: "FC Barcelona",
        Edad: 18,
        PosicionPrincipal:"Extremo Izquierdo",
        PosicionesSecundarias:["Delantero Centro","Extremo Derecho"],
        PieHabil:"Derecho",
        Valor: 80000000, 
        Estadisticas:{Partidos: 33,Goles: 8,Asistencias: 1 },
        Altura: 1.78,
      } ,

      {
        Jugador:"Ferland Mendy",
        Nacionalidad:"Francia",
        Liga:"Liga Española",
        Equipo: "Real Madrid CF",
        Edad: 25,
        PosicionPrincipal:"Lateral Izquierdo",
        PosicionesSecundarias:["Interior Izquierdo"],
        PieHabil:"Izquierdo",
        Valor: 40000000, 
        Estadisticas:{Partidos: 32,Goles: 1,Asistencias: 4 },
        Altura: 1.80,
      } ,

      {
        Jugador:"Jules Kounde",
        Nacionalidad:"Francia",
        Liga:"Liga Española",
        Equipo: "Sevilla FC",
        Edad: 22,
        PosicionPrincipal:"Defensa Central",
        PosicionesSecundarias:["Lateral Derecho"],
        PieHabil:"Derecho",
        Valor: 40000000, 
        Estadisticas:{Partidos: 40,Goles: 2,Asistencias: 1 },
        Altura: 1.78,
      } ,

      {
        Jugador:"Diego Carlos",
        Nacionalidad:"Brasil",
        Liga:"Liga Española",
        Equipo: "Sevilla FC",
        Edad: 27,
        PosicionPrincipal:"Defensa Central",
        PosicionesSecundarias:[],
        PieHabil:"Derecho",
        Valor: 50000000, 
        Estadisticas:{Partidos: 45,Goles: 2,Asistencias: 1 },
        Altura: 1.86,
      } ,

      {
        Jugador:"Ter Stegen",
        Nacionalidad:"Alemania",
        Liga:"Liga Española",
        Equipo: "FC Barcelona",
        Edad: 28,
        PosicionPrincipal:"Portero",
        PosicionesSecundarias:[],
        PieHabil:"Derecho",
        Valor: 75000000, 
        Estadisticas:{Partidos: 46,Goles: 0,Asistencias: 0, GolesContra:50 },
        Altura: 1.87,
      } ,

      {
        Jugador:"Thibaut Courtois",
        Nacionalidad:"Belgica",
        Liga:"Liga Española",
        Equipo: "Real Madrid CF",
        Edad: 28,
        PosicionPrincipal:"Portero",
        PosicionesSecundarias:[],
        PieHabil:"Izquierdo",
        Valor: 75000000, 
        Estadisticas:{Partidos: 43,Goles: 0,Asistencias: 0, GolesContra:32 },
        Altura: 1.99,
      } ,

      {
        Jugador:"Alphonso Davies",
        Nacionalidad:"Canada",
        Liga:"Liga Alemana",
        Equipo: "Bayern Munich",
        Edad: 20,
        PosicionPrincipal:"Lateral Izquierdo",
        PosicionesSecundarias:["Extremo Izquierdo","Extremo Derecho"],
        PieHabil:"Izquierdo",
        Valor: 80000000, 
        Estadisticas:{Partidos: 46,Goles: 3,Asistencias: 10 },
        Altura: 1.81,
      } ,

      {
        Jugador:"Robert Lewandowski",
        Nacionalidad:"Polonia",
        Liga:"Liga Alemana",
        Equipo: "Bayern Munich",
        Edad: 32,
        PosicionPrincipal:"Delantero Centro",
        PosicionesSecundarias:["Mediapunta"],
        PieHabil:"Derecho",
        Valor: 60000000, 
        Estadisticas:{Partidos: 47,Goles: 55,Asistencias: 10 },
        Altura: 1.84,
      } ,

      {
        Jugador:"Paulo Dybala",
        Nacionalidad:"Argentina",
        Liga:"Liga Italiana",
        Equipo: "Juventus",
        Edad: 26,
        PosicionPrincipal:"Mediapunta",
        PosicionesSecundarias:["Delantero Centro","Extremo Derecho"],
        PieHabil:"Izquierdo",
        Valor: 80000000, 
        Estadisticas:{Partidos: 46,Goles: 17,Asistencias: 14 },
        Altura: 1.77,
      } ,

      {
        Jugador:"Fabinho",
        Nacionalidad:"Brasil",
        Liga:"Liga Inglesa",
        Equipo: "Liverpool FC",
        Edad: 27,
        PosicionPrincipal:"Pivote",
        PosicionesSecundarias:["Defensa Central","Lateral Derecho"],
        PieHabil:"Derecho",
        Valor: 60000000, 
        Estadisticas:{Partidos: 39,Goles: 2,Asistencias: 4 },
        Altura: 1.88,
      } ,

      {
        Jugador:"Frankie De Jong",
        Nacionalidad:"Holanda",
        Liga:"Liga Española",
        Equipo: "FC Barcelona",
        Edad: 23,
        PosicionPrincipal:"Mediocentro",
        PosicionesSecundarias:["Pivote","Defensa Central"],
        PieHabil:"Derecho",
        Valor: 70000000, 
        Estadisticas:{Partidos: 42,Goles: 2,Asistencias: 4 },
        Altura: 1.81,
      } ,

      {
        Jugador:"Ngolo Kante",
        Nacionalidad:"Francia",
        Liga:"Liga Inglesa",
        Equipo: "Chelsea",
        Edad: 29,
        PosicionPrincipal:"Mediocentro",
        PosicionesSecundarias:["Pivote"],
        PieHabil:"Derecho",
        Valor: 70000000, 
        Estadisticas:{Partidos: 28,Goles: 3,Asistencias: 0 },
        Altura: 1.68,
      } ,

      {
        Jugador:"Marco Reus",
        Nacionalidad:"Alemania",
        Liga:"Liga Alemana",
        Equipo: "Borussia Dortmund",
        Edad: 31,
        PosicionPrincipal:"Mediapunta",
        PosicionesSecundarias:["Delantero Centro","Extremo Izquierdo"],
        PieHabil:"Derecho",
        Valor: 25000000, 
        Estadisticas:{Partidos: 26,Goles: 12,Asistencias: 7 },
        Altura: 1.80,
      } ,

      {
        Jugador:"Fernando Reges",
        Nacionalidad:"Brasil",
        Liga:"Liga Española",
        Equipo: "Sevilla FC",
        Edad: 33,
        PosicionPrincipal:"Pivote",
        PosicionesSecundarias:["Defensa Central","Mediocentro"],
        PieHabil:"Derecho",
        Valor: 4000000, 
        Estadisticas:{Partidos: 42,Goles: 3,Asistencias: 3 },
        Altura: 1.83,
      } ,

      {
        Jugador:"Luka Modric",
        Nacionalidad:"Croacia",
        Liga:"Liga Española",
        Equipo: "Real Madrid CF",
        Edad: 35,
        PosicionPrincipal:"Mediocentro",
        PosicionesSecundarias:["Mediapunta","Pivote"],
        PieHabil:"Derecho",
        Valor: 10000000, 
        Estadisticas:{Partidos: 40,Goles: 5,Asistencias: 8 },
        Altura: 1.72,
      } ,

      {
        Jugador:"Leon Goretzka",
        Nacionalidad:"Alemania",
        Liga:"Liga Alemana",
        Equipo: "Bayern Munich",
        Edad: 25,
        PosicionPrincipal:"Mediocentro",
        PosicionesSecundarias:["Mediapunta","Interior Derecho"],
        PieHabil:"Derecho",
        Valor: 60000000, 
        Estadisticas:{Partidos: 38,Goles: 8,Asistencias: 11 },
        Altura: 1.89,
      } ,

      {
        Jugador:"Eduardo Camavinga",
        Nacionalidad:"Francia",
        Liga:"Liga Francesa",
        Equipo: "Stade Rennais",
        Edad: 18,
        PosicionPrincipal:"Mediocentro",
        PosicionesSecundarias:["Pivote"],
        PieHabil:"Izquierdo",
        Valor: 50000000, 
        Estadisticas:{Partidos: 36,Goles: 1,Asistencias: 2 },
        Altura: 1.82,
      } ,

      {
        Jugador:"Gianluigi Donnarumma",
        Nacionalidad:"Italia",
        Liga:"Liga Italiana",
        Equipo: "AC Milan",
        Edad: 21,
        PosicionPrincipal:"Portero",
        PosicionesSecundarias:[],
        PieHabil:"Derecho",
        Valor: 60000000, 
        Estadisticas:{Partidos: 39,Goles: 0,Asistencias: 0, GolesContra:45 },
        Altura: 1.96,
      } ,

      {
        Jugador:"Sergio Asenjo",
        Nacionalidad:"Española",
        Liga:"Liga Española",
        Equipo: "Villarreal CF",
        Edad: 31,
        PosicionPrincipal:"Portero",
        PosicionesSecundarias:[],
        PieHabil:"Derecho",
        Valor: 9000000, 
        Estadisticas:{Partidos: 34,Goles: 0,Asistencias: 0, GolesContra:41 },
        Altura: 1.89,
      } ,


      {
        Jugador:"Bruno Fernandes",
        Nacionalidad:"Portugal",
        Liga:"Liga Inglesa",
        Equipo: "Manchester United",
        Edad: 26,
        PosicionPrincipal:"Mediapunta",
        PosicionesSecundarias:["Mediocentro","Interior Derecho"],
        PieHabil:"Derecho",
        Valor: 80000000, 
        Estadisticas:{Partidos: 50,Goles: 27,Asistencias: 22 },
        Altura: 1.79,
      } ,

      {
        Jugador:"Kevin De Bruyne",
        Nacionalidad:"Belgica",
        Liga:"Liga Inglesa",
        Equipo: "Manchester City",
        Edad: 29,
        PosicionPrincipal:"Mediapunta",
        PosicionesSecundarias:["Mediocentro","Interior Derecho","Interior Izquierdo"],
        PieHabil:"Derecho",
        Valor: 120000000, 
        Estadisticas:{Partidos: 48,Goles: 16,Asistencias: 23 },
        Altura: 1.81,
      } ,

      {
        Jugador:"Keylor Navas",
        Nacionalidad:"Costa Rica",
        Liga:"Liga Francesa",
        Equipo: "Paris Saint Germain",
        Edad: 33,
        PosicionPrincipal:"Portero",
        PosicionesSecundarias:[],
        PieHabil:"Derecho",
        Valor: 10000000, 
        Estadisticas:{Partidos: 35,Goles: 0,Asistencias: 0, GolesContra:26 },
        Altura: 1.85,
      } ,


     



])